<a href="https://colab.research.google.com/github/darshnkd/TensorFlow-Fundamentals/blob/main/00_tenserflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook : Fundamentals of tensors using tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function(a way to speed up your regular python function)
* Using GPUs with TensorFlow (TPUs)
* Exercise



Introduction to tensors

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)


2.15.0


In [ ]:
# create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
# create vector
vector = tf.constant([10,24])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 24], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create matrix ( has more than 1 dimension)
matrix = tf.constant([[2,3],
                      [4,5]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [11.,12]], dtype=tf.float16)# specify the data type as dtype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [11., 12.]], dtype=float16)>

In [ ]:
# Let's check the dimension of another matrix
another_matrix.ndim

2

In [ ]:
# let's create tensor
Tensor =tf.constant([[[1,2,3],
                      [2,3,4]],
                    [[1,23,3],
                     [5,6,6]],
                     [[1,2,3],
                     [7,4,8]]])
Tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 1, 23,  3],
        [ 5,  6,  6]],

       [[ 1,  2,  3],
        [ 7,  4,  8]]], dtype=int32)>

In [ ]:
Tensor.ndim

3

#so far:
* sclar : a single number
* vector : a number with direction
* matrix : a two dimensional array of number
* tensor : a n dimensional array of number (for eg 0 dimensional tensor is sclar and 1 dimensional is vector)


# creating tensor with tf.variable

---



In [ ]:
# create tensor using tf.variable
changeable_tensor = tf.Variable([10,24])
unchangeable_tensor = tf.constant([10,24])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 24], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 24], dtype=int32)>)

In [ ]:
# lets try to change the element in our tensor(using .assign())
# you can't change the unchangable_tensor using .assign()
changeable_tensor[1].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>

### random tensors
* random tensors are tensors of some abitrary size which contain some random number


In [ ]:
# create two random (but the same ) tensor
# create generator with specific seed
random_1 = tf.random.Generator.from_seed(7) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))


In [ ]:
# Are the equal?
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#### shuffle the order of element in tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order dosen't affect learning)
not_shuffled = tf.constant([[10,24],
                            [3,4],
                            [11,12]])
not_shuffled,not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 24],
        [ 3,  4],
        [11, 12]], dtype=int32)>,
 2)

In [ ]:
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10, 24],
       [11, 12]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # this is global and this can't shuffle
tf.random.shuffle(not_shuffled,seed=42) # this is local / operational level seed that shuffle the tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 24],
       [ 3,  4],
       [11, 12]], dtype=int32)>

In [ ]:
# create tensor of all ones
tf.ones([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeros
tf.zeros([10,8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#### create numpy array in to tensors
The main difference between numpy array and tensorflow tensor is that tensor can be run on GPU(much faster for numerical computing)


In [ ]:
# You can create numpy array in to tensor
import numpy as np
numpy_A = np.arange(1,25, dtype= np.int32) # create a numpy array between 1 to 24
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# numpy array in to tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# change the shape of tensor
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

In [ ]:
A = tf.constant(numpy_A,shape=(2,12))
A

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

#### Getting information from tensor
when dealing with tensor you probably want to be aware of the following attribute
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# lets create rank 4 tensor (4 dimension )
rank_four_tensor = tf.ones(shape=(2,3,4,5))
rank_four_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_four_tensor[0,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
rank_four_tensor.shape[-1]

5

In [ ]:
rank_four_tensor.ndim, rank_four_tensor.shape, tf.size(rank_four_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
print("Data type of every element in tensor : ",rank_four_tensor.dtype)
print("Number of element in tensor : ", tf.size(rank_four_tensor))
print("Shape of the tensor :  ",rank_four_tensor.shape)
print("Dimension or rank of the tensor : ",rank_four_tensor.ndim)
print("element along the 0 axis : ",rank_four_tensor.shape[0])
print("element along the last axis : ", rank_four_tensor.shape[-1])

Data type of every element in tensor :  <dtype: 'float32'>
Number of element in tensor :  tf.Tensor(120, shape=(), dtype=int32)
Shape of the tensor :   (2, 3, 4, 5)
Dimension or rank of the tensor :  4
element along the 0 axis :  2
element along the last axis :  5


###Indexing tensor
tensor can be indexed like just python list

In [ ]:
rank_four_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except final one
rank_four_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[1.]],

        [[1.]]]], dtype=float32)>

In [ ]:
# create rank two tensor
rank_two_tensor = tf.constant([[10,24],
                               [1,2]])
rank_two_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 24],
       [ 1,  2]], dtype=int32)>

In [ ]:
rank_two_tensor.ndim

2

In [ ]:
# get the last item of each of row of our rank two tensor
rank_two_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([24,  2], dtype=int32)>

In [ ]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_two_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [24]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
# the altrenative to tf.newaxis
tf.expand_dims(rank_two_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [24]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
# Expand 0-axis tensor
tf.expand_dims(rank_two_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 24],
        [ 1,  2]]], dtype=int32)>

#### Manipulating tensors(tensor operations)
Basic operation (+ , - , * , / )

In [ ]:
# adding values to our tensor
tensor = tf.constant([[10,24],
                     [1,2]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 34],
       [11, 12]], dtype=int32)>

In [ ]:
# multiplication you can do if you want
tensor  * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 240],
       [ 10,  20]], dtype=int32)>

In [ ]:
# division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 2.4],
       [0.1, 0.2]])>

In [ ]:
# subtraction
tensor - 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 14],
       [-9, -8]], dtype=int32)>

In [ ]:
# there are tensorflow library function as well
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 240],
       [ 10,  20]], dtype=int32)>

In [ ]:
tf.add(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 34],
       [11, 12]], dtype=int32)>

In [ ]:
tf.subtract(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,   4],
       [-19, -18]], dtype=int32)>

In [ ]:
tf.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 2.4],
       [0.1, 0.2]])>

***Matrix Multiplication***
* In machine learning , matrix multipliction is one of the most common operation.
* There are two rules our tensors(or matrix) need to fulfil if we are going to matrix multiply them.
1. The inner dimension must match.
2. The resulting matrix has the shape of the outer dimension.

In [ ]:
# Matrix multiplication in tenserflow
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 24],
       [ 1,  2]], dtype=int32)>

In [ ]:
tf.matmul(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 288],
       [ 12,  28]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 576],
       [  1,   4]], dtype=int32)>

In [ ]:
# matrix multiplication in python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 288],
       [ 12,  28]], dtype=int32)>

In [ ]:
# Let's create tensor (3,2) shape
x = tf.constant([[1,2],
                  [4,2],
                  [9,5]])

In [ ]:
# create another tensor of same size
y = tf.constant([[7,5],
                 [4,5],
                 [1,9]])

In [ ]:
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 2],
        [9, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[7, 5],
        [4, 5],
        [1, 9]], dtype=int32)>)

In [ ]:
#x @ y # need to follow two rule or conditions
# To change the shape either you can transpose or reshape

In [ ]:
# transpose of y
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 14, 19],
       [38, 26, 22],
       [88, 61, 54]], dtype=int32)>

In [ ]:
# multiplication of x and transposed y
x @ tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 14, 19],
       [38, 26, 22],
       [88, 61, 54]], dtype=int32)>

In [ ]:
# reshaping x
x , tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 2],
        [9, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [2, 9, 5]], dtype=int32)>)

In [ ]:
# check the shape of x and reshape(x)
x.shape , tf.reshape(x,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# multiplication of reshape(x) and y
tf.matmul(tf.reshape(x,shape=(2,3)),y) , y.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 19,  51],
        [ 55, 100]], dtype=int32)>,
 TensorShape([3, 2]))

In [ ]:
#🛠️ Now you can transpose x and do all multiplication operation

In [ ]:
# Check values of x , transpose of (x) and reshape of (x)
print("Normal x : ")
print(x , "\n")

print("Transpose of x : ")
print(tf.transpose(x) , "\n")

print("Reshape of x : ")
print(tf.reshape(x,shape=(2,3)))

Normal x : 
tf.Tensor(
[[1 2]
 [4 2]
 [9 5]], shape=(3, 2), dtype=int32) 

Transpose of x : 
tf.Tensor(
[[1 4 9]
 [2 2 5]], shape=(2, 3), dtype=int32) 

Reshape of x : 
tf.Tensor(
[[1 2 4]
 [2 9 5]], shape=(2, 3), dtype=int32)


In [ ]:
# Check values of y , reshape of (y) and transpose of (y)
print("Normal y : ")
print(y , "\n")

print("Transpose of y : ")
print(tf.transpose(y) , "\n")

print("Reshape of y : ")
print(tf.reshape(y,shape=(2,3)))

Normal y : 
tf.Tensor(
[[7 5]
 [4 5]
 [1 9]], shape=(3, 2), dtype=int32) 

Transpose of y : 
tf.Tensor(
[[7 4 1]
 [5 5 9]], shape=(2, 3), dtype=int32) 

Reshape of y : 
tf.Tensor(
[[7 5 4]
 [5 1 9]], shape=(2, 3), dtype=int32)


***Dot product***

Matrix multiplication is also referred as the dot product.

You can perform matrix multiplication using :
* tf.matmmul()
* tf.tensordot()


In [ ]:
# perform the dot product on x and y (requires x or y to be transpose)
c = tf.tensordot(x,tf.transpose(y),axes=1)  # it has one more argument which is axes
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 14, 19],
       [38, 26, 22],
       [88, 61, 54]], dtype=int32)>

In [ ]:
d = tf.tensordot(x, tf.reshape(y,shape=(2,3)) , axes=1)
d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [38, 22, 34],
       [88, 50, 81]], dtype=int32)>

In [ ]:
c , d

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[17, 14, 19],
        [38, 26, 22],
        [88, 61, 54]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[17,  7, 22],
        [38, 22, 34],
        [88, 50, 81]], dtype=int32)>)

##### Generally when performing matrix multiplication on two tensor and one of the axes dosen't line up , you will transpose rather than(reshape) one of tensor to satisfy matrix multiplication rules.

### Changing the datatype of tensor

In [ ]:
# Create a new tensor with default datatype (float32)
A = tf.constant([10.2,24.1])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.2, 24.1], dtype=float32)>

In [ ]:
# Create another tensor with default datatype(int32)
B = tf.constant([10,24])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 24], dtype=int32)>

In [ ]:
# Let's change the datatype (float32 to float16)
C = tf.cast(A,dtype=tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.2, 24.1], dtype=float16)>

In [ ]:
#  change the datatype (int32 to int16)
D = tf.cast(B,dtype=tf.int16)
D


<tf.Tensor: shape=(2,), dtype=int16, numpy=array([10, 24], dtype=int16)>

In [ ]:
# From int to float
E = tf.cast(D,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 24.], dtype=float32)>

In [ ]:
# similarly you can do float to int

#### Aggregating tensor

Aggregating tensor = combining multiple tensors in some way to produce a single tensor.

In [ ]:
# get the absolute values
M = tf.constant([-10,-24])
M

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10, -24], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(M)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 24], dtype=int32)>

Let's go through the following form of aggregation.
* Get the min
* Get the max
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Creat random tensor
N = tf.random.uniform(shape=(50,),minval=0,maxval=100, dtype=tf.int32)
N

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([87, 89, 61, 86, 92, 84, 83, 43, 71, 91, 52, 40, 51, 81, 20,  8, 59,
       32,  9, 99, 11, 12, 97, 94, 19,  1, 61, 45,  6, 15, 70, 52,  1, 23,
       68, 65,  3, 50,  3, 88, 52, 38,  1, 19, 92, 54, 82, 79, 39, 36],
      dtype=int32)>

In [ ]:
# Find the minimum value
tf.reduce_min(N)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
#  Find the maximum value
tf.reduce_max(N)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [ ]:
#  Find the mean value
tf.reduce_mean(N)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [ ]:
# Find the sum value (total value)
tf.reduce_sum(N)

<tf.Tensor: shape=(), dtype=int32, numpy=2514>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(N,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.589897>

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(N,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=997.9216>

In [ ]:
# Check the version
tf.__version__

'2.15.0'

### Find the positional maximum and minimum

In [ ]:
# Create new tensor to find positional minimum and maximum
Z = tf.random.uniform(shape=[50])
Z

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
# value on our largest value index position
Z[tf.argmax(Z)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869994>

In [ ]:
# Find the max value of Z
tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869994>

In [ ]:
# Check the equality
Z[tf.argmax(Z)] == tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [ ]:
# Find the minimum using positional minimum index
Z[tf.argmin(Z)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.013772249>

In [ ]:
# Find the min value of Z
tf.reduce_min(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.013772249>

In [ ]:
# Check equality again for min
Z[tf.argmin(Z)] == tf.reduce_min(Z)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor ( removing all single dimension)

In [ ]:
# Create a tensor to get started
L = tf.random.uniform(shape=(1,1,1,1,50))
L

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [ ]:
# squeeze the tensosr
L_squeezed = tf.squeeze(L)
L_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

In [ ]:
L.shape , L_squeezed.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Create a list of indices
list = [0,1,2,3,5] # red ,green , blue , yellow, orange
list

[0, 1, 2, 3, 5]

In [ ]:
# encode our list with indices
tf.one_hot(list , depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# specify custom value for one hot encoding
tf.one_hot(list , depth = 5 , on_value="Yes" , off_value="NO")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Yes', b'NO', b'NO', b'NO', b'NO'],
       [b'NO', b'Yes', b'NO', b'NO', b'NO'],
       [b'NO', b'NO', b'Yes', b'NO', b'NO'],
       [b'NO', b'NO', b'NO', b'Yes', b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'NO']], dtype=object)>

### Squaring , log ,square root

In [ ]:
# Create tensor first.
J = tf.range( 1 , 20)
J

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [ ]:
# Square the tensor
tf.square(J)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)>

In [ ]:
# Find the square root
tf.sqrt(tf.cast(J,dtype=(tf.float32)))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249, 3.4641016,
       3.6055512, 3.7416575, 3.8729835, 4.       , 4.1231055, 4.2426405,
       4.358899 ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(J , dtype=(tf.float32)))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

### Tensors and numpy
Tensorflow interact beautifuly with numpy

In [ ]:
# Creat a tensor directly from numpy array
P = tf.constant(np.array([3.,5.,7.]))
P

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 7.])>

In [ ]:
# Convert our tensor back to numpy
np.array(P) , type(np.array(P))

(array([3., 5., 7.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5.,7.]))
tensor_J = tf.constant([3.,5.,7.])
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
P.numpy()

array([3., 5., 7.])